feature: add constant
altendky/stlib pull request #23
Opened 2021-06-07 18:58 UTC by epcAnker

adding constant as an interface item.

Related:
PM: https://github.com/altendky/pm/pull/15
grid-tied: epcpower/grid-tied#71
embedded lib : epcpower/embedded-library#24

2021-06-21 20:51 UTC, altendky reviewed
Is read only a property of the SunSpec data point?  Should there be a check on export or such to ensure that constant parameters aren't attached to not-read-only SunSpec data points?  It feels like there should be something somewhere, maybe.

2021-06-22 15:30 UTC, epcAnker commented on epyqlib/attrsmodel.py
> +        if s.isdecimal():
will be removing this and adding it back in the next story.  Will make some adjustments based on this comment in the next story.

2021-06-22 15:30 UTC, epcAnker commented on epyqlib/attrsmodel.py
> +            return None
same as above

2021-06-22 15:55 UTC, altendky requested changes
There are some test failures.  The first one looks good.  The second one looks like a somewhat annoying test.  If I remember correctly you can take the output and paste it into the sample file then check the diff with git and make sure the changes are what you intended.

https://ci.appveyor.com/project/KyleAltendorf/stlib/builds/39703883#L2890
```
__________________ TestAttrsModel.test_all_fields_in_columns __________________
self = <epyqlib.attrsmodel.BuiltTests object at 0x0000020B0CC45D88>
    def test_all_fields_in_columns(self):
        fields = set()
    
        for cls in self.types:
            if cls is self.root_type:
                continue
    
            for field in epyqlib.attrsmodel.fields(cls):
                if field.no_column:
                    continue
    
                fields.add((cls, field.name))
    
        columns_list = [
            tuple(x)
            for x in itertools.chain(*(column.items() for column in self.columns))
            if x[0] is not self.root_type
        ]
    
        columns = set(columns_list)
    
        assert len(columns_list) == len(columns)
    
        extra = columns - fields
        missing = fields - columns
    
        assert extra == set()
>       assert missing == set(), columns_to_code(missing)
E       AssertionError: 
E         ((Parameter, 'constant'),),
E       assert {(<class 'epyqlib.pm.parametermodel.Parameter'>, 'constant')} == set()
E         Extra items in the left set:
E         (<class 'epyqlib.pm.parametermodel.Parameter'>, 'constant')
E         Full diff:
E         - {(<class 'epyqlib.pm.parametermodel.Parameter'>, 'constant')}
E         + set()
epyqlib\attrsmodel.py:1616: AssertionError
```

2021-06-22 17:46 UTC, epcAnker commented
> Is read only a property of the SunSpec data point? Should there be a check on export or such to ensure that constant parameters aren't attached to not-read-only SunSpec data points? It feels like there should be something somewhere, maybe.

test

2021-06-24 14:15 UTC, altendky approved these changes
It might be worth it at some point to add an entry to the example that has a constant specified.

2021-06-25 14:15 UTC, merged